#cloud-config

datasource:
  Ec2:
    timeout: 60
    max_wait: 60
    metadata_urls:
      - http://169.254.169.254
      - http://instance-data

package_update: true
package_upgrade: true

fs_setup:
  - label: data
    filesystem: ext4
    device: /dev/xvdd

mounts:
  - [ /dev/xvdd, /var/lib/redis, "auto" ]

packages:
- docker.io
- jq
- awscli

write_files:
- path: /etc/aws/aws.conf
  permissions: '0644'
  content: |
    [Global]
    Zone = ${aws_region}
- path: /etc/redis/redis.conf
  permissions: '0644'
  content: |
    # redis-server configuration file
    port ${redis_port}
    requirepass "${redis_pass}"
    rename-command CONFIG ""
    rename-command SHUTDOWN ""
- path: /etc/default/redis-server
  permissions: '0644'
  content: |
    # redis-server configure options
- path: /etc/default/redis-spiped
  permissions: '0644'
  content: |
    # redis-spiped configure options
- path: /etc/systemd/system/redis-server.service
  permissions: '0644'
  content: |
    [Unit]
    Description=The Redis Server container
    After=docker.service
    Requires=docker.service
    PartOf=docker.service
    [Service]
    EnvironmentFile=/etc/default/redis-server
    ExecStartPre=-/usr/bin/docker rm -f redis-server
    ExecStart=/usr/bin/docker run --name redis-server --hostname $(hostname).${cluster_id} --rm -v /var/lib/redis:/var/lib/redis:z -v /etc/redis:/etc/redis:ro --env-file=/etc/default/redis-server --network=bridge -p ${redis_port}:${redis_port} redis:${redis_version} /etc/redis/redis.conf
    ExecStop=/usr/bin/docker stop redis-server
    SyslogIdentifier=redis-server
    Restart=always
    RestartSec=5s
    [Install]
    WantedBy=docker.service
- path: /etc/systemd/system/redis-spiped.service
  permissions: '0644'
  content: |
    [Unit]
    Description=The Redis spiped container
    After=redis-server.service
    Requires=redis-server.service
    PartOf=docker.service
    [Service]
    EnvironmentFile=/etc/default/redis-spiped
    ExecStartPre=-/usr/bin/docker rm -f redis-spiped
    ExecStart=/usr/bin/docker run --name redis-spiped --hostname $(hostname).${cluster_id} --rm -v /etc/spiped:/etc/spiped:z --env-file=/etc/default/redis-spiped --network=host -p ${redis_port}:${redis_port} --link redis-server spiped:alpine
    ExecStop=/usr/bin/docker stop redis-spiped
    SyslogIdentifier=redis-spiped
    Restart=always
    RestartSec=5s
    [Install]
    WantedBy=docker.service
- path: /spiped/key/spiped-keyfile
  permissions: '0600'
  content: ${enc_key}


runcmd:
- systemctl daemon-reload
- systemctl enable redis-server redis-spiped
- systemctl start redis-server redis-spiped
