#cloud-config

datasource:
  Ec2:
    timeout: 60
    max_wait: 60
    metadata_urls:
      - http://169.254.169.254
      - http://instance-data

apt:
  sources:
    docker-ce.list:
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable"
      keyid: 0EBFCD88

package_update: true
package_upgrade: true

fs_setup:
  - label: data
    filesystem: ext4
    device: /dev/xvdd

mounts:
  - [ /dev/xvdd, /var/lib/redis, "auto" ]

packages:
- linux-image-extra-virtual
- apt-transport-https
- software-properties-common
- docker-ce
- jq
- awscli

write_files:
- path: /etc/aws/aws.conf
  permissions: '0644'
  content: |
    [Global]
    Zone = ${aws_region}
- path: /etc/redis/redis.conf
  permissions: '0644'
  content: |
    # redis-server configuration file
    port ${redis_port}
    requirepass "${redis_pass}"
    rename-command CONFIG ""
    rename-command SHUTDOWN ""
- path: /etc/default/redis-server
  permissions: '0644'
  content: |
    # redis-server configure options
- path: /etc/default/redis-spiped
  permissions: '0644'
  content: |
    # redis-spiped configure options
- path: /etc/systemd/system/redis-server.service
  permissions: '0644'
  content: |
    [Unit]
    Description=The Redis Server container
    After=docker.service
    Requires=docker.service
    PartOf=docker.service
    [Service]
    EnvironmentFile=/etc/default/redis-server
    ExecStartPre=-/usr/bin/docker rm -f redis-server
    ExecStart=/usr/bin/docker run --name redis-server --hostname $(hostname).${cluster_id} --rm -v /var/lib/redis:/var/lib/redis:z -v /etc/redis:/etc/redis:ro --env-file=/etc/default/redis-server --network=none -p ${redis_port}:${redis_port} redis:${redis_version} /etc/redis/redis.conf
    ExecStop=/usr/bin/docker stop redis-server
    SyslogIdentifier=redis-server
    Restart=always
    RestartSec=5s
    [Install]
    WantedBy=docker.service
- path: /etc/systemd/system/redis-spiped.service
  permissions: '0644'
  content: |
    [Unit]
    Description=The Redis spiped container
    After=redis-server.service
    Requires=redis-server.service
    PartOf=docker.service
    [Service]
    EnvironmentFile=/etc/default/redis-spiped
    ExecStartPre=-/usr/bin/docker rm -f redis-spiped
    ExecStart=/usr/bin/docker run --name redis-spiped --hostname $(hostname).${cluster_id} --rm -v /etc/spiped/.key:/spiped/key:ro --env-file=/etc/default/redis-spiped --network=bridge -p ${redis_port}:${redis_port} --link redis-server --init spiped:alpine -d -s '[0.0.0.0]:${redis_port}' -t 'redis-server:${redis_port}'
    ExecStop=/usr/bin/docker stop redis-spiped
    SyslogIdentifier=redis-spiped
    Restart=always
    RestartSec=5s
    [Install]
    WantedBy=docker.service
- path: /etc/spiped/.key
  permissions: '0600'
  content: ${enc_key}


runcmd:
- systemctl daemon-reload
- systemctl enable redis-server redis-spiped
- systemctl start redis-server redis-spiped
